site_name: BulletBuzz
site_description: Bullet Heaven Game Documentation
site_author: tjsingleton

repo_name: tjsingleton/bulletbuzz
repo_url: https://github.com/tjsingleton/bulletbuzz

theme:
  name: material
  logo: logo.png
  favicon: favicon.ico
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Features:
    - Event System: features/event-system.md
  - API Reference:
    - Generated API Docs: api/index.html
  - Testing:
    - Unit Testing: testing/unit-testing.md
    - Integration Testing: testing/integration-testing.md
    - Screenshot Testing: testing/screenshot-testing.md
    - Test Coverage Report: testing/test-coverage-report.md
    - Performance Testing: testing/performance-testing.md
    - Headless Simulation: testing/headless-simulation.md

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tjsingleton/bulletbuzz

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - mermaid-init.js 