site_name: BulletBuzz
site_description: Auto-Battler Game Documentation
site_author: tjsingleton

repo_name: tjsingleton/bulletbuzz
repo_url: https://github.com/tjsingleton/bulletbuzz

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - API Reference:
    - Game API: api/game-api.md
    - AI API: api/ai-api.md
    - Configuration API: api/configuration-api.md
    - Screenshot API: api/screenshot-api.md
    - Testing API: api/testing-api.md
  - Testing:
    - Unit Testing: testing/unit-testing.md
    - Integration Testing: testing/integration-testing.md
    - Performance Testing: testing/performance-testing.md
    - Screenshot Testing: testing/screenshot-testing.md
    - Headless Simulation: testing/headless-simulation.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tjsingleton/bulletbuzz 