name: Deploy Game and Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript game
      run: npm run build
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install MkDocs
      run: pip install mkdocs mkdocs-material
      
    - name: Build documentation
      run: mkdocs build
      
    - name: Organize site structure
      run: |
        set -e
        echo "Contents of project root after build:"
        ls -l
        mkdir -p site/game
        cp index.html site/game/
        cp -r dist site/game/
        cp assets/logo.png assets/favicon.ico assets/logo-192.png assets/logo-512.png site/game/ || true
        cp assets/game-screenshot.png site/
        cp README.md site/
        cp LICENSE site/
        echo "Contents of site/game after copy:"
        ls -l site/game
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 