name: Deploy Game and Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript game
      run: npm run build
      
    - name: Build with Version
      run: node scripts/build-with-version.js
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install MkDocs
      run: pip install mkdocs mkdocs-material
      
    - name: Build documentation
      run: mkdocs build
      
    - name: Organize site structure
      run: ./scripts/deploy-organize-site.sh
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Wait for deployment
      run: |
        echo "⏳ Waiting 60 seconds for deployment to propagate..."
        sleep 60
        
    - name: Test deployment
      run: ./scripts/deploy-test-site.sh 